services:
  # SERVIÃ‡O DE BANCO DE DADOS
  db:
    image: postgres:15-alpine
    container_name: paylure-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - paylure-db-data:/var/lib/postgresql/data
    networks:
      - paylure-network
    # ðŸš¨ CORREÃ‡ÃƒO FINAL: Healthcheck para garantir que o DB esteja pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Damos mais tempo para o DB iniciar
  # SERVIÃ‡O DO BACKEND (NESTJS)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: paylure-backend
    container_name: paylure-api
    restart: always
    # ðŸš¨ CORREÃ‡ÃƒO FINAL: Depende do DB estar saudÃ¡vel antes de iniciar
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
      PORT: 3000 # Lendo a porta do .env
    ports:
      - 3000:3000
    networks:
      - paylure-network

# Volumes: NecessÃ¡rio para persistir os dados do Banco de Dados
volumes:
  paylure-db-data:
    driver: local
networks:
  paylure-network:
    driver: bridge
