name: paylure

services:
  db:
    image: postgres:15-alpine
    container_name: paylure-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - paylure-db-data:/var/lib/postgresql/data
    networks:
      - paylure-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: paylure-backend
    container_name: paylure-api
    restart: always
    depends_on:
      db:
        condition: service_healthy

    # ✅ Lê o .env e injeta no container
    env_file:
      - .env

    # (Opcional) Se quiser forçar algumas envs aqui:
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - RESEND_API_KEY=${RESEND_API_KEY}

    ports:
      - "3030:3000"
    networks:
      - paylure-network

volumes:
  paylure-db-data:

networks:
  paylure-network:
    driver: bridge
