version: "3.8"
services:
  # SERVI√áO DE BANCO DE DADOS
  db:
    image: postgres:15-alpine
    container_name: paylure-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - paylure-db-data:/var/lib/postgresql/data
    networks:
      - paylure-network
  # SERVI√áO DO BACKEND (NESTJS)
  api:
    # üö® CORRE√á√ÉO ESSENCIAL: Adicionar a instru√ß√£o 'build' para construir a imagem localmente
    build:
      context: .
      dockerfile: Dockerfile
    image: paylure-backend
    container_name: paylure-api
    restart: always
    depends_on:
      - db
    environment:
      # As vari√°veis de ambiente ser√£o lidas do arquivo .env
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
      # Adicionando a vari√°vel de ambiente para o NestJS saber em qual porta rodar
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - paylure-network

# Volumes: Necess√°rio para persistir os dados do Banco de Dados
volumes:
  paylure-db-data:
    driver: local
networks:
  paylure-network:
    driver: bridge
